[build.environment]
  NODE_VERSION = "16.15.0"
  NPM_FLAGS = ""

[build]
  base = "/"
  publish = "./docs/build/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build --filter=docs"

[context.deploy-preview.environment]
  NODE_ENV = "Preview"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
