[build.environment]
  NODE_VERSION = "14"
  NPM_FLAGS = "--prefix=/dev/null"
[build]
  base = "/"
  publish = "./docs/build/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build --filter=docs"
[context.deploy-preview.environment]
  NODE_ENV = "Preview"
